# Q1

In [5]:
import numpy as np
import matplotlib.pyplot as plt
import math
import libsvm
import csv
from csv import reader
from libsvm.svmutil import *

def read_csv(upload):
    x=[]
    y=[]
    file = open(upload,'r')
    r = reader(file)
    for row in r:
        x.append(row[:-1])
        y.append(row[-1])

    return [x,y]

upload = "p3_train.csv"
data = read_csv(upload)

#Convert the matrix into a float
#data=array(data)

#Extract the last column as the target variable
#y_train=data[:,-1]
#deleting the last column from the data and appending a column of 1s infront of it. 
#x_train=data[:,:-1]
#one=np.ones((data.shape[0], 1))
#data=np.hstack((one,data))
#col=data.shape[1]

y_train=data[1]
x_train=data[0]

L=len(y_train)
for i in range(L):
    y_train[i]=float(y_train[i])
    y_train[i]=int(y_train[i])
    
for row in x_train:
    l=len(row)
    for idx in range(l):
        row[idx]=float(row[idx])

In [6]:
y_tr=y_train[:10000]
x_tr=x_train[:10000]

In [7]:
upload = "p3_test.csv"
data_test = read_csv(upload)

y_test=data_test[1]
x_test=data_test[0]

L=len(y_test)
for i in range(L):
    y_test[i]=float(y_test[i])
    y_test[i]=int(y_test[i])
    
for row in x_test:
    l=len(row)
    for idx in range(l):
        row[idx]=float(row[idx])

Examples of options: -s 0 -c 10 -t 1 -g 1 -r 1 -d 3
Classify a binary data with polynomial kernel $(u'v+1)^3$ and C = 10

 
options:

-s svm_type : set type of SVM (default 0)

	0 -- C-SVC
    
	1 -- nu-SVC
    
	2 -- one-class SVM
    
	3 -- epsilon-SVR
    
	4 -- nu-SVR
    
-t kernel_type : set type of kernel function (default 2)

	0 -- linear: u'*v
    
	1 -- polynomial: (gamma*u'*v + coef0)^degree
    
	2 -- radial basis function: exp(-gamma*|u-v|^2)
    
	3 -- sigmoid: tanh(gamma*u'*v + coef0)
    
-d degree : set degree in kernel function (default 3)

-g gamma : set gamma in kernel function (default 1/num_features)

-r coef0 : set coef0 in kernel function (default 0)

-c cost : set the parameter C of C-SVC, epsilon-SVR, and nu-SVR (default 1)

-n nu : set the parameter nu of nu-SVC, one-class SVM, and nu-SVR (default 0.5)

-p epsilon : set the epsilon in loss function of epsilon-SVR (default 0.1)

-m cachesize : set cache memory size in MB (default 100)

-e epsilon : set tolerance of termination criterion (default 0.001)

-h shrinking: whether to use the shrinking heuristics, 0 or 1 (default 1)

-b probability_estimates: whether to train a SVC or SVR model for probability estimates, 0 or 1 (default 0)

-wi weight: set the parameter C of class i to weight*C, for C-SVC (default 1)

The k in the -g option means the number of attributes in the input data.

In [8]:
prob  = svm_problem(y_tr, x_tr)
param = svm_parameter('-s 0 -t 0 -c 4 -d 3')
m = svm_train(prob, param)

In [9]:
p_label, p_acc, p_val = svm_predict(y_test, x_test, m)

Accuracy = 56.52% (8478/15000) (classification)


In [18]:
l_p=len(p_label)
for i in range(l_p):
    p_label[i]=int(p_label[i])

In [19]:
labels=len(np.unique(y_test))
c_mat=np.zeros((labels, labels))
l=len(y_test)
for i in range(l):
    c_mat[y_test[i]-1][p_label[i]-1]+=1
print(c_mat)


[[1580.  387.  245.  366.  393.]
 [ 417. 1645.  268.  290.  361.]
 [ 351.  313. 1779.  279.  318.]
 [ 399.  330.  228. 1708.  310.]
 [ 379.  313.  232.  343. 1766.]]


In [34]:
F_s=[]
precision=[]
rec=[]
for i in range(labels):
    prec=c_mat[i][i]/np.sum(c_mat[:,i])
    recall=c_mat[i][i]/np.sum(c_mat[i])
    f= (2*prec*recall)/(prec+recall)
    precision.append(prec)
    rec.append(recall)
    F_s.append(f)

print("F_score is:", F_s)
print("precision is:", precision)
print("Recall is:", rec)

F_score is: [0.5182876824667869, 0.5511811023622047, 0.6142955801104971, 0.5730582117094447, 0.5714285714285714]
precision is: [0.5054382597568778, 0.5505354752342704, 0.6464389534883721, 0.5720026791694575, 0.5609911054637865]
Recall is: [0.5318074722315719, 0.5518282455551828, 0.5851973684210526, 0.5741176470588235, 0.5822617870095614]


### Now, fitting with polynomial functions

##### Polynomial of degree 3

In [21]:
prob  = svm_problem(y_tr, x_tr)
param = svm_parameter('-s 0 -t 1 -c 4 -d 3')
m = svm_train(prob, param)

In [22]:
p_label, p_acc, p_val = svm_predict(y_test, x_test, m)

Accuracy = 55.2733% (8291/15000) (classification)


##### Polynomial of degree 5

In [28]:
prob1  = svm_problem(y_tr, x_tr)
param1 = svm_parameter('-s 0 -t 1 -c 4 -d 5')
m1 = svm_train(prob1, param1)

In [29]:
p_label, p_acc, p_val = svm_predict(y_test, x_test, m1)

Accuracy = 46.8% (7020/15000) (classification)


##### Increasing the cost of misclassification

In [31]:
prob2  = svm_problem(y_tr, x_tr)
param2 = svm_parameter('-s 0 -t 1 -c 50 -d 3')
m2 = svm_train(prob2, param2)

In [35]:
p_label, p_acc, p_val = svm_predict(y_test, x_test, m2)

Accuracy = 55.0733% (8261/15000) (classification)


Increasing the cost takes significantly longer time. Trying with 2nd degree polynomial.

In [36]:
prob3  = svm_problem(y_tr, x_tr)
param3 = svm_parameter('-s 0 -t 1 -c 5 -d 2')
m3 = svm_train(prob3, param3)

In [37]:
p_label, p_acc, p_val = svm_predict(y_test, x_test, m3)

Accuracy = 51.4267% (7714/15000) (classification)


### Trying with RBF kernel

In [38]:
prob4  = svm_problem(y_tr, x_tr)
param4 = svm_parameter('-s 0 -t 2 -c 5')
m4 = svm_train(prob4, param4)

In [39]:
p_label, p_acc, p_val = svm_predict(y_test, x_test, m4)

Accuracy = 55.44% (8316/15000) (classification)


### Sigmoid Kernel

In [40]:
prob5  = svm_problem(y_tr, x_tr)
param5 = svm_parameter('-s 0 -t 3 -c 5')
m5 = svm_train(prob5, param5)

In [41]:
p_label, p_acc, p_val = svm_predict(y_test, x_test, m5)

Accuracy = 32.5533% (4883/15000) (classification)


Bad accuracy.

##### Reducing the cost to low, to allow slacked formulation

In [10]:
prob6  = svm_problem(y_tr, x_tr)
param6 = svm_parameter('-s 0 -t 0 -c 0.5')
m6 = svm_train(prob6, param6)

In [11]:
p_label, p_acc, p_val = svm_predict(y_test, x_test, m6)

Accuracy = 56.5467% (8482/15000) (classification)


In [13]:
prob7  = svm_problem(y_tr, x_tr)
param7 = svm_parameter('-s 0 -t 0 -c 0.1')
m7 = svm_train(prob7, param7)

In [14]:
p_label, p_acc, p_val = svm_predict(y_test, x_test, m7)

Accuracy = 56.5867% (8488/15000) (classification)


In [17]:
prob8  = svm_problem(y_tr, x_tr)
param8 = svm_parameter('-s 0 -t 0 -c 0.0001')
m8 = svm_train(prob8, param8)

In [18]:
p_label, p_acc, p_val = svm_predict(y_test, x_test, m8)

Accuracy = 56.3733% (8456/15000) (classification)
