## Q4

In [22]:
import numpy as np

a=[]
b=np.array([5,5,5])
c=np.append(a,b)
np.append(c,b)

array([5., 5., 5., 5., 5., 5.])

In [14]:
print(c)

[5. 5. 5.]


In [15]:
import numpy as np
import matplotlib.pyplot as plt
import math
from csv import reader

In [16]:
def read_csv(upload):
    x=[]
    y=[]
    file = open(upload,'r')
    r = reader(file)
    count=1
    for row in r:
        if(count>1):
            x.append(row[1:])
            y.append(row[0])
        count+=1
    return [x,y]

upload = "PCA_MNIST.csv"
data = read_csv(upload)

In [19]:
y_train=data[1]
x_train=np.array(data[0]).astype(np.float64)/255

In [20]:
print(x_train)

[[ 2.36583291 -1.04300844  0.1158567  ... -0.15809439  1.49486139
  -0.74364461]
 [ 1.17062016 -0.38252849  0.20823531 ...  0.95752241  0.99508716
   1.02971592]
 [-1.66910643  2.53392258  1.70043943 ... -1.56686864  1.35998079
  -0.50619125]
 ...
 [-2.2308468   0.0233176   1.84563781 ... -0.87445603  0.5879309
  -0.63711032]
 [ 3.02643918 -0.41482651  1.16273309 ... -0.33012283  0.2826223
   0.35619552]
 [ 1.5660565   0.87363992  0.63290923 ... -0.54816256  0.39747253
   0.5829402 ]]


In [35]:
a=np.matrix([3,5])
b=np.matrix([3,5])

c=a.T@b
print(c)

[[ 9 15]
 [15 25]]


In [37]:
a=np.array([[5,4,6,7],[5,6,7,8]])
a.T

array([[5, 5],
       [4, 6],
       [6, 7],
       [7, 8]])

In [6]:
import numpy as np

x=np.arange(100)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
